# Generated by Django 4.2.8 on 2023-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryData',
            fields=[
                ('Lead_Status', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duplicate_lead', models.CharField(max_length=100)),
                ('new_lead', models.CharField(max_length=100)),
                ('grand_total', models.CharField(max_length=100)),
                ('overall_qualification', models.CharField(max_length=100)),
                ('new_lead_qualification', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'primary_data',
            },
        ),
    ]
